n1= int(input("Digite o primeiro numero: "))
n2= int(input("Digite o segundo numero: "))
n3= float(input("Digite o terceiro numero: "))
print("Exibindo, o produto do dobro do primeiro com metade do segundo ",(n1*2)*(n2/2))
print("Exibindo, a soma do triplo do primeiro com o terceiro ",n1*3+n3)
print("Exibindo o terceiro numero elevado ao cubo ", n3**3)
